### ISSUE TITLE
Portland compilers on Tegner

### ISSUE THREAD

**Issue by wikfeldt** [PDC-support/PDC-support-web#1]
in the development section (documents/running/development.html) only gnu and intel compilers are mentioned. How about the portland compilers? (module show pgi/15.1)

**Comment by menzzana** [comment]
yes, we do have Portland compiler on Tegner, but not with OpenMPI support, so it seems just for serial jobs or OpenMP jobs?
pgf90, pgcc pgc++
and then use -mp flag for OpenMP

I do not think anybody is using it though and think it is unnecessary to support OpenMPI for it
