### ISSUE TITLE
standardize command line format

### ISSUE THREAD

**Issue by wikfeldt** [PDC-support/PDC-support-web#12]
use $ or no symbol at the start of terminal commands? Skipping the $ is more useful for copy-paste work

**Comment by menzzana** [comment]
I agree, but with one exception.
In the linux tutorial we mix output and input so it is good to differentiate between the 2.
Also in this case not much copy/paste is being done

**Comment by menzzana** [comment]
I have removed all $ but instead highlighted with new background color. I really wanted to bold command text but have not found a good way to do that yet

**Comment by menzzana** [comment]
Changed theme to alabaster to better reflect this
