### ISSUE TITLE
"where to store my data" needs work

### ISSUE THREAD

**Issue by wikfeldt** [PDC-support/PDC-support-web#13]
The (beginner) and (advanced) subsections should need some more work. Also, the (advanced) section promises to help the user choose storage option, but no such advice is given.

**Comment by menzzana** [comment]
We do not have information about iRODS yet. Perhaps the advanced section will be clearer after Dejans presentation

**Comment by menzzana** [comment]
remove advanced store data, and edit beginner so that it show "where to store my data" Future support
for iRods will be more separate
