### ISSUE TITLE
AFS on Mac

### ISSUE THREAD

**Issue by menzzana** [PDC-support/PDC-support-web#16]
See

https://www.pdc.kth.se/resources/software/file-transfer/file-transfer-with-afs/mac/afs-on-mac-1/version_diff?version_id1=9&version_id2=8

and https://lists.openafs.org/pipermail/openafs-info/2017-September/042202.html

Which should be included in the documentation

**Comment by wikfeldt** [comment]
fixed in 5bf205ee40425109137d12a19368dc27b3ac3aa2
