### ISSUE TITLE
add table with slurm options for tegner

### ISSUE THREAD

**Issue by wikfeldt** [PDC-support/PDC-support-web#22]
similar to the old table here:
https://www-old.pdc.kth.se/resources/computers/tegner/hardware

**Comment by menzzana** [comment]
That is already done at https://www.pdc.kth.se/support/documents/running/running_jobs/job_scripts_tegner.html
but we need a SLURM table for Beskow as well, since nowadays it has different kinds of nodes

**Comment by menzzana** [comment]
you can specify partitions on Beskow with the -p <partition ID>
broadwell is in the bw36 partition
