### ISSUE TITLE
Lustre file system is called klemming

### ISSUE THREAD

**Issue by menzzana** [PDC-support/PDC-support-web#3]
Although we do use klemming as a nick-name it is the Lustre filesystem, otherwise
it could be confusing for ex. /cfs/scania /cfs/rydberg which are the same filesystem.

**Comment by Harimus** [comment]
Last commit: the file "klemming.rst" was renamed to "lustre.rst". With (vimgrep) recursively through the repository, "Klemming" was changed to "Lustre" (and sentence corrected), without changing directory path explanation such as ' cfs/klemming/nobackup ' . It should be fixed, with another words
