### ISSUE TITLE
Scrolling After Clicking on Subpage Broken

### ISSUE THREAD

**Issue by rmsthebest** [PDC-support/PDC-support-web#43]
Sometimes after you click on a subsection for a page, for example https://www.pdc.kth.se/support/documents/starting/get_account.html#apply-via-pdc-webpage
The page is kind of cut off above that and you can't scroll up to the top of the page again

**Comment by menzzana** [comment]
I cannot really reproduce this error on my laptop (Linux mint latest) and chrome.
Is it perhaps localized to KTH Ubuntu?

**Comment by wikfeldt** [comment]
yes it must be the integration into polopoly. I see it on mac+chrome as well. 
As far as I can see it has to do with headers, like in this url:
https://www.pdc.kth.se/support/documents/development.html#compiling-dynamically

If I put this url in a new browser tab, the page loads in the middle where the #compiling-dynamically section is. If I then scroll up, a random amount of the upper parts of the page are missing (repeating the process leads to different amounts of missing content). But, if I then refresh the page, it loads completely but the browser shows it from the top (i.e. the #compiling-dynamically part of the url is ignored)

**Comment by tourkaman** [comment]
It seems like the working and non-working versions have differing (loaded) source codes.

I tried preventing RTD's javascripts from getting loaded, but the problems persist.
These problems are probably caused by PoloPoly itself.

I just contacted our PoloPoly "consultat"; Waiting to hear from him.

**Comment by tourkaman** [comment]
Problem potentially solved.
Would you please check and see if the problem has gone away for you?

#### Solution
I noticed an inconsistency in the way that the pages were getting distorted when comparing the two different example pages provided by @rmsthebest and @wikfeldt which made me question one particular jQuery file on PoloPoly which was there to ironically correct the page positioning.
Disabling it made this bug go away. I assume this is due to some deeper change in PoloPoly that we didn't get to hear about since this used to work properly at the time.

I still haven't heard back from our PoloPoly person.

**Comment by rmsthebest** [comment]
It appears to be fixed.
I spent a few minutes trying to replicated the bug but it never occurs.

**Comment by recoli** [comment]
My case: Chrome and Safari work well, but Firefox still has the problem.

**Comment by tourkaman** [comment]
Once again, and hopefully for the last time, problem solved :)

#### The Solution
Our polopoly person didn't seem to have any idea (beyond suggesting that maybe some javascript is responsible for it) but from what I can see this has to do with one line of CSS in the core kth.se styling.

I solved it by adding the following (Mozilla extension) to the support part of the website
```css
body #page { overflow: -moz-hidden-unscrollable !important }
```
which overrides the default one loaded from kth.se which is
```css
body #page { overflow: hidden }
```

**For the record,** in the process I also disabled ALL of my custom javascripts but the problem persisted and it was first after having confirmed that I wasn't the one responsible for this that I uploaded the solution to the system.
