### ISSUE TITLE
Add top-level entry "Courses" 

### ISSUE THREAD

**Issue by recoli** [PDC-support/PDC-support-web#50]
Suggestion from Thor:

Add a top-level entry “Courses” to our support pages, next to “Industry”.

It would contain a short summary of how to log in etc, with links to the rest of the docs, and some links to exercises and such.

There should also be a place where students could start and click their way to find general information and lab exercises.

**Comment by wikfeldt** [comment]
I'm working on a feature branch for this, pull request coming tomorrow

**Comment by wikfeldt** [comment]
fixed in 08e4333551d66e9448a59f421f1a0780905dcf48, closing issue
