### ISSUE TITLE
add instructions on SNIC env variables

### ISSUE THREAD

**Issue by wikfeldt** [PDC-support/PDC-support-web#9]
Describe environment variables
$SNIC_BACKUP, $SNIC_NOBACKUP, $SNIC_RESOURCE, $SNIC_SITE, $SNIC_TMP
On Tegner one needs "module add snic-env", while they're set by default on Beskow.
Maybe talk to Lars about removing the defaults on Beskow and using a module instead

**Comment by menzzana** [comment]
We will get some user complaints if removed on Beskow, so perhaps its better to just create a module there, and lets leave it for next generation clusters
